
mysql:
  servicePort: 3306
  providerPort: 33306
  image:
    repository: "docker.io/nick170/librenms-mysql"
    tag: "0.1.8"
  prepareVolumeImage:
    repository: "docker.io/nick170/librenms-mysql-prepare-volume"
    tag: "0.1.8"
  storage:
    type: dynamic
    # for .storage.type 'dynamic' ...
    subpathRequired: true
    class: ssd
    size: 100Gi
    # for .storage.type 'static' ...
    claimName:
  external:
    enabled: false
    # for .storage.external.enabled true ...
    address:
    port: 3306

rrdcached:
  servicePort: 42217
  providerPort: 42217
  chunkSize: 2
  threadCount: 2
  flushInterval: 600
  writeInterval: 300
  writeDelay: 5
  logLevel: "LOG_NOTICE"
  image:
    repository: "docker.io/nick170/librenms-rrdcached"
    tag: "0.1.8"
  storage:
    type: dynamic
    # for .storage.type 'dynamic' ...
    subpathRequired: true
    class: standard
    size: 100Gi
    # for .storage.type 'static' ...
    claimName:
  external:
    enabled: false
    # for .storage.external.enabled true ...
    address:
    port: 42217

memcached:
  servicePort: 11211
  providerPort: 11211
  threadCount: 2
  connectionRequests: 10
  logLevel: ""
  image:
    repository: "docker.io/nick170/librenms-memcached"
    tag: "0.1.8"

redis:
  servicePort: 6379
  providerPort: 36379
  logLevel: "notice"
  image:
    repository: "docker.io/nick170/librenms-redis"
    tag: "0.1.8"
  storage:
    type: dynamic
    # for .storage.type 'dynamic' ...
    subpathRequired: true
    class: ssd
    size: 100Gi
    # for .storage.type 'static' ...
    claimName:

subpath:
  image:
    repository: "docker.io/nick170/librenms-subpath"
    tag: "0.1.8"

